apiVersion: v1
kind: Service
metadata:
    name: authorization
    labels:
        app: authorization
spec:
    ports:
    - port: 80
      targetPort: 80
    type: NodePort
    selector:
        app: authorization
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
    name: authorization
spec:
    replicas: 2
    selector:
      matchLabels:
        app: authorization
    template:
        metadata:
          labels:
            app: authorization
            tier: service
        spec:
            containers:
            - name: authorization
              image: eamonwoortman/alpine-python-curl-zip
              command: ["python"]
              args: ["./server.py"]
              env:
                - name: MICROSERVICE
                  valueFrom:
                    configMapKeyRef:
                      name: authorization-env
                      key: svc.name
              workingDir: /server
              ports:
              - containerPort: 80
              volumeMounts:
              - mountPath: /server
                name: nfs-share
            volumes:
            - name: nfs-share
              hostPath:
                path: /opt/kdata

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: authorization-env
  namespace: default
data:
  svc.name: authorization
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata: 
  name: authorization
  annotations: 
    kubernetes.io/ingress.class: traefik
  labels:
    ingress-tier: service
spec:
  rules:
  - http: 
      paths:
      - path: /api/authorization
        backend: 
          serviceName: authorization
          servicePort: 80